name: Deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - LICENSE
      - '**.md'
      - 'renovate.json'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install global dependencies
        run: npm i -g eslint
      - name: Lint the repository
        run: npm run lint
      - name: Update the application in real-time
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: 22
          username: august
          password: ${{ secrets.PASSWORD }}

          # TODO: use docker
          script: |
            cd ~/webhooks
            git pull
            rm -fr node_modules
            rm yarn.lock
            yarn
            pm2 restart webhooks
