name: ESLint
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'assets/**'
      - '.gitignore'
      - LICENSE
      - '**.md'
      - 'renovate.json'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
  
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install global dependencies
        run: npm i -g eslint

      - name: Install local dependencies
        run: npm i

      - name: Lint the repository
        run: npm run lint
